const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('nexusAPI', {
    sincronizarProductoServidor: (productData) => ipcRenderer.invoke('sincronizar-producto-servidor', productData),
    obtenerProductosLocal: (empresaId) => ipcRenderer.invoke('obtener-productos-local', empresaId),
    obtenerCategoriasLocal: () => ipcRenderer.invoke('obtener-categorias-local'),
    sincronizarCategoriaServidor: (cat) => ipcRenderer.invoke('sincronizar-categoria-servidor', cat),
    eliminarCategoriaLocal: (id) => ipcRenderer.invoke('eliminar-categoria-local', id),
    sincronizarCategoriasLocal: (categories) => ipcRenderer.invoke('sincronizar-categorias-local', categories),
    guardarUsuarioLocal: (datos) => ipcRenderer.invoke('guardar-usuario-local', datos),
    obtenerSesionLocal: () => ipcRenderer.invoke('obtener-sesion-local'),
    loginLocal: (email) => ipcRenderer.invoke('login-local', email),
    cerrarSesionLocal: () => ipcRenderer.invoke('cerrar-sesion-local'),
    guardarClienteLocal: (cliente) => ipcRenderer.invoke('guardar-cliente-local', cliente),
    obtenerClientesLocal: () => ipcRenderer.invoke('obtener-clientes-local'),
    guardarTasaBCV: (tasa) => ipcRenderer.invoke('guardar-tasa-bcv', tasa),
    obtenerTasaBCV: () => ipcRenderer.invoke('obtener-tasa-bcv'),
    obtenerHistorialTasas: () => ipcRenderer.invoke('obtener-historial-tasas'),
    obtenerConfiguracion: (key) => ipcRenderer.invoke('obtener-configuracion', key),
    guardarConfiguracion: (key, data) => ipcRenderer.invoke('guardar-configuracion', key, data),
    leerImpresoras: () => ipcRenderer.invoke('leer-impresoras'),
    leerPuertos: () => ipcRenderer.invoke('leer-puertos'),
    imprimirTextoLibre: (texto, nombreImpresora) => ipcRenderer.invoke('imprimir-texto-libre', texto, nombreImpresora),
    minimize: () => ipcRenderer.send('minimize-login-window'),
    close: () => ipcRenderer.send('close-login-window'),
    cerrarYVolverAlLogin: () => ipcRenderer.send('cerrar-y-volver-login'),
    abrirVentanaPrincipal: (ruta) => ipcRenderer.send('abrir-ventana-principal', ruta),
    encolarSincronizacion: (tarea) => ipcRenderer.invoke('encolar-sincronizacion', tarea),
    procesarColaSync: () => ipcRenderer.invoke('procesar-cola-sync'),
    consultarIA: (datos) => ipcRenderer.invoke('consultar-ia-nexus', datos),
    guardarVentaLocal: (venta) => ipcRenderer.invoke('guardar-venta-local', venta),
    obtenerProximoCorrelativo: (tipo) => ipcRenderer.invoke('obtener-proximo-correlativo', tipo),
    obtenerVentaPorId: (id) => ipcRenderer.invoke('obtener-venta-por-id', id),
    onProductosCambiados: (callback) => {ipcRenderer.removeAllListeners('productos-actualizados'); ipcRenderer.on('productos-actualizados', () => callback());},
    guardarSucursalLocal: (sucursal) => ipcRenderer.invoke('guardar-sucursal-local', sucursal),
    obtenerSucursalesLocal: (companyId) => ipcRenderer.invoke('obtener-sucursales-local', companyId),
    obtenerInventarioSucursal: (datos) => ipcRenderer.invoke('obtener-inventario-sucursal', datos),
    guardarStockSucursal: (datos) => ipcRenderer.invoke('guardar-stock-sucursal', datos),
    obtenerUnidadesEmpaqueLocal: (companyId) => ipcRenderer.invoke('obtener-unidades-empaque-local', companyId),
    guardarUnidadEmpaqueLocal: (datos) => ipcRenderer.invoke('guardar-unidad-empaque-local', datos),
    eliminarUnidadEmpaqueLocal: (id) => ipcRenderer.invoke('eliminar-unidad-empaque-local', id),
    obtenerEmpaquePorProducto: (productId) => ipcRenderer.invoke('obtener-empaque-por-producto', productId),
    guardarSalidaLocal: (datos) => ipcRenderer.invoke('guardar-salida-local', datos),
    obtenerSalidasLocal: (filtro) => ipcRenderer.invoke('obtener-salidas-local', filtro),
    obtenerConfiguracionCajera: (key) => ipcRenderer.invoke('obtener-configuracion-cajera', key),
    guardarConfiguracionCajera: (key, data) => ipcRenderer.invoke('guardar-configuracion-cajera', key, data),
    sincronizarConfiguracionXeon: (datos) => ipcRenderer.invoke('sincronizar-configuracion-xeon', datos),
    iniciarLecturaPuerto: (puerto) => ipcRenderer.send('iniciar-puerto-balanza', puerto),
    onPesoRecibido: (callback) => ipcRenderer.on('peso-desde-balanza', (event, data) => callback(data)),

});

console.log('✅ Puente NexusAPI establecido correctamente.');