const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('nexusAPI', {
    sincronizarProductoServidor: (productData) => ipcRenderer.invoke('sincronizar-producto-servidor', productData),
    obtenerProductosLocal: (empresaId) => ipcRenderer.invoke('obtener-productos-local', empresaId),
    obtenerCategoriasLocal: () => ipcRenderer.invoke('obtener-categorias-local'),
    sincronizarCategoriaServidor: (cat) => ipcRenderer.invoke('sincronizar-categoria-servidor', cat),
    eliminarCategoriaLocal: (id) => ipcRenderer.invoke('eliminar-categoria-local', id),
    sincronizarCategoriasLocal: (categories) => ipcRenderer.invoke('sincronizar-categorias-local', categories),
    guardarUsuarioLocal: (datos) => ipcRenderer.invoke('guardar-usuario-local', datos),
    obtenerSesionLocal: () => ipcRenderer.invoke('obtener-sesion-local'),
    loginLocal: (email) => ipcRenderer.invoke('login-local', email),
    cerrarSesionLocal: () => ipcRenderer.invoke('cerrar-sesion-local'),
    guardarClienteLocal: (cliente) => ipcRenderer.invoke('guardar-cliente-local', cliente),
    obtenerClientesLocal: () => ipcRenderer.invoke('obtener-clientes-local'),
    guardarTasaBCV: (tasa) => ipcRenderer.invoke('guardar-tasa-bcv', tasa),
    obtenerTasaBCV: () => ipcRenderer.invoke('obtener-tasa-bcv'),
    obtenerHistorialTasas: () => ipcRenderer.invoke('obtener-historial-tasas'),
    obtenerConfiguracion: (key) => ipcRenderer.invoke('obtener-configuracion', key),
    guardarConfiguracion: (key, data) => ipcRenderer.invoke('guardar-configuracion', key, data),
    leerImpresoras: () => ipcRenderer.invoke('leer-impresoras'),
    leerPuertos: () => ipcRenderer.invoke('leer-puertos'),
    imprimirTextoLibre: (texto, nombreImpresora) => ipcRenderer.invoke('imprimir-texto-libre', texto, nombreImpresora),
    minimize: () => ipcRenderer.send('minimize-login-window'),
    close: () => ipcRenderer.send('close-login-window'),
    cerrarYVolverAlLogin: () => ipcRenderer.send('cerrar-y-volver-login'),
    abrirVentanaPrincipal: (ruta) => ipcRenderer.send('abrir-ventana-principal', ruta),
    encolarSincronizacion: (tarea) => ipcRenderer.invoke('encolar-sincronizacion', tarea),
    consultarIA: (datos) => ipcRenderer.invoke('consultar-ia-nexus', datos),
    guardarVentaLocal: (venta) => ipcRenderer.invoke('guardar-venta-local', venta),
    obtenerProximoCorrelativo: (tipo) => ipcRenderer.invoke('obtener-proximo-correlativo', tipo),
    verificarYDescontarStockMaestro: (datos) => ipcRenderer.invoke('verificar-y-descontar-stock-maestro', datos),
    obtenerVentaPorId: (id) => ipcRenderer.invoke('obtener-venta-por-id', id),
    onProductosCambiados: (callback) => {ipcRenderer.removeAllListeners('productos-actualizados'); ipcRenderer.on('productos-actualizados', () => callback());},
    guardarSucursalLocal: (sucursal) => ipcRenderer.invoke('guardar-sucursal-local', sucursal),
    obtenerSucursalesLocal: (companyId) => ipcRenderer.invoke('obtener-sucursales-local', companyId),
    obtenerInventarioSucursal: (datos) => ipcRenderer.invoke('obtener-inventario-sucursal', datos),
    guardarStockSucursal: (datos) => ipcRenderer.invoke('guardar-stock-sucursal', datos),
    obtenerUnidadesEmpaqueLocal: (companyId) => ipcRenderer.invoke('obtener-unidades-empaque-local', companyId),
    guardarUnidadEmpaqueLocal: (datos) => ipcRenderer.invoke('guardar-unidad-empaque-local', datos),
    eliminarUnidadEmpaqueLocal: (id) => ipcRenderer.invoke('eliminar-unidad-empaque-local', id),
    obtenerEmpaquePorProducto: (productId) => ipcRenderer.invoke('obtener-empaque-por-producto', productId),
    guardarSalidaLocal: (datos) => ipcRenderer.invoke('guardar-salida-local', datos),
    obtenerSalidasLocal: (filtro) => ipcRenderer.invoke('obtener-salidas-local', filtro),
    obtenerConfiguracionCajera: (key) => ipcRenderer.invoke('obtener-configuracion-cajera', key),
    guardarConfiguracionCajera: (key, data) => ipcRenderer.invoke('guardar-configuracion-cajera', key, data),
    iniciarLecturaPuerto: (puerto) => ipcRenderer.send('iniciar-puerto-bascula', puerto),
    tarearBalanza: () => ipcRenderer.send('tarear-bascula'),
    onPesoRecibido: (callback) => {ipcRenderer.removeAllListeners('peso-recibido');ipcRenderer.on('peso-recibido', (event, peso) => callback(peso));},
    guardarMovimientoCaja: (datos) => ipcRenderer.invoke('guardar-movimiento-caja', datos),
    obtenerMovimientosCaja: (filtro) => ipcRenderer.invoke('obtener-movimientos-caja', filtro),
    guardarClaveAdminLocal: (datos) => ipcRenderer.invoke('guardar-clave-admin-local', datos),
    obtenerClavesAdminLocal: (companyId) => ipcRenderer.invoke('obtener-claves-admin-local', companyId),
    eliminarClaveAdminLocal: (id) => ipcRenderer.invoke('eliminar-clave-admin-local', id),
    eliminarClienteLocal: (rif) => ipcRenderer.invoke('eliminar-cliente-local', rif),
    crearRespaldoLocal: () => ipcRenderer.invoke('crear-respaldo-local'),
    obtenerRespaldosLocales: () => ipcRenderer.invoke('obtener-respaldos-locales'),
    eliminarRespaldoLocal: (fileName) => ipcRenderer.invoke('eliminar-respaldo-local', fileName),
    restaurarRespaldoLocal: (fileName) => ipcRenderer.invoke('restaurar-respaldo-local', fileName),
    apagarSistema: () => ipcRenderer.send('apagar-sistema'),
    reiniciarAplicacion: () => ipcRenderer.invoke('reiniciar-aplicacion'),
    obtenerVentasPendientesCaja: (datos) => ipcRenderer.invoke('obtener-ventas-pendientes-caja', datos),
    procesarCierreCajaLocal: (datos) => ipcRenderer.invoke('procesar-cierre-caja-local', datos),
    registrarDeudaMaestro: (datos) => ipcRenderer.invoke('registrar-deuda-maestro', datos),
    registrarAbonoMaestro: (datos) => ipcRenderer.invoke('registrar-abono-maestro', datos),
    obtenerDeudaClienteMaestro: (rif) => ipcRenderer.invoke('obtener-deuda-cliente-maestro', rif),
    imprimirFacturaFiscal: (saleData) => ipcRenderer.invoke('imprimir-factura-fiscal', saleData),
    consultarEstadoFiscal: () => ipcRenderer.invoke('consultar-estado-fiscal'),
    iniciarAuthWorkerHKA: (credentials) => ipcRenderer.send('ejecutar-auth-hka', credentials),
    onHkaAuthLog: (callback) => ipcRenderer.on('hka-auth-log', (event, message) => callback(message)),
    emitirFacturaHKA: (facturaJSON) => ipcRenderer.invoke('emitir-factura-hka', facturaJSON),
    obtenerBorradoresMaestro: (sucursalId, companyId) => ipcRenderer.invoke('obtener-borradores-maestro', { sucursalId, companyId }),
    guardarBorradorMaestro: (datos) => ipcRenderer.invoke('guardar-borrador-maestro', datos),
    eliminarBorradorMaestro: (id) => ipcRenderer.invoke('eliminar-borrador-maestro', id),
    obtenerIpMaestro: () => ipcRenderer.invoke('obtener-ip-maestro'),
    guardarPagoMovil: (datos) => ipcRenderer.invoke('guardar-pago-movil', datos),
    obtenerPagosMovilesCaja: (datos) => ipcRenderer.invoke('obtener-pagos-moviles-caja', datos),
    procesarCierreCajaLocal: (datos) => ipcRenderer.invoke('procesar-cierre-caja-local', datos),
    obtenerHistorialCierres: (companyId) => ipcRenderer.invoke('obtener-historial-cierres', { companyId }),
    obtenerConfigServer: () => ipcRenderer.invoke('get-config'),
    obtenerColaSincronizacion: () => ipcRenderer.invoke('obtener-cola-sincronizacion'),
    eliminarDeCola: (id) => ipcRenderer.invoke('eliminar-de-cola', id),
    guardarConfiguracionMaestra: (datos) => ipcRenderer.invoke('guardar-config-maestra', datos),
    leerConfiguracionMaestra: (clave) => ipcRenderer.invoke('leer-config-maestra', clave),
    guardarClaveAdminMaestro: (datos) => ipcRenderer.invoke('guardar-clave-admin-maestro', datos),
    obtenerClavesAdminMaestro: (companyId) => ipcRenderer.invoke('obtener-claves-admin-maestro', companyId),
    eliminarClaveAdminMaestro: (id) => ipcRenderer.invoke('eliminar-clave-admin-maestro', id),
    obtenerFacturaLocal: (numFactura) => ipcRenderer.invoke('obtener-factura-local', numFactura),
    marcarComoSincronizado: (tabla, id) => ipcRenderer.invoke('marcar-como-sincronizado', tabla, id),
    descargarEInstalar: (url) => ipcRenderer.invoke('descargar-update', url),
    onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (_event, value) => callback(value)),
    verificarActualizacion: (versionLocal) => ipcRenderer.invoke('verificar-actualizacion-github', versionLocal),
    obtenerVersionApp: () => ipcRenderer.invoke('obtener-version-app'),
    editarArchivoEnvLocal: (nuevaConfig) => ipcRenderer.invoke('editar-env-local', nuevaConfig),
    guardarPlanLocal: (planData) => ipcRenderer.invoke('guardar-plan-local', planData),
    obtenerPlanLocal: (companyId) => ipcRenderer.invoke('obtener-plan-local', companyId),
    eliminarSucursalLocal: (id) => ipcRenderer.invoke('eliminar-sucursal-local', id),
    guardarAuditoriaAdmin: (datos) => ipcRenderer.invoke('guardar-auditoria-admin', datos),
    obtenerAuditoriaAdmin: (companyId) => ipcRenderer.invoke('obtener-auditoria-admin', companyId),
    validarSaldoNC: (nroFactura) => ipcRenderer.invoke('validar-saldo-nc', nroFactura),
    registrarRetencionIVA: (datos) => ipcRenderer.invoke('registrar-retencion-iva', datos),
    obtenerFacturasPendientesRetencion: (rif) => ipcRenderer.invoke('obtener-facturas-pendientes-retencion', { rif }),
    guardarGuiaDespachoMaestro: (datos) => ipcRenderer.invoke('guardar-guia-despacho-maestro', datos),
    consultarEstadoFiscal: (puerto) => ipcRenderer.invoke('consultar-estado-fiscal', puerto),
    emitirTramasHKA: (tramas, puerto) => ipcRenderer.invoke('emitir-tramas-hka', tramas, puerto),
    onSolicitarVerificacionCierre: (callback) => ipcRenderer.on('solicitar-verificacion-cierre', (event) => callback()),
    confirmarCierreSeguro: () => ipcRenderer.send('confirmar-cierre-seguro'),
    
});

console.log('✅ Puente NexusAPI establecido correctamente.');